name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login into Docker Registery
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "ms43" --password-stdin

    - name: Login into Github Docker Registery
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ms43 --password-stdin

    - uses: denolib/setup-deno@master
      with:
        deno-version: v1.x

    - name: Run Docker
      run: deno run --allow-net --allow-run build.ts
